import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const posts = await (await fetch("http://localhost:4000/posts")).json();

  return (
    <html lang="ko">
      <body className="p-4">{children}</body>
    </html>
  );
}
